name: deploy-service
description: Deploy greetings service on to selected environment

inputs:
  env_name:
    required: true
  port:
    required: true
  app_path:
    required: true

runs:
  using: "composite"
  steps:
    - name: Stop previous PM2 service
      shell: cmd
      run: |
        pm2 delete greetings-app-${{ inputs.env_name }} & EXIT /B 0
    
    - name: Clone python-greetings repository
      uses: actions/checkout@v6
      with:
        repository: mtararujs/python-greetings
        path: ${{ inputs.app_path }}

    - name: Print deploy info
      shell: cmd
      run: echo Deploying to %INPUT_ENV_NAME%...

    - name: Create virtual environment
      shell: cmd
      working-directory: ${{ inputs.app_path }}
      run: python -m venv venv

    - name: Install requirements
      shell: cmd
      working-directory: ${{ inputs.app_path }}
      run: |
        venv\Scripts\python -m pip install --upgrade pip
        venv\Scripts\python -m pip install -r requirements.txt
    
    - name: Start service with PM2
      shell: cmd
      working-directory: ${{ inputs.app_path }}
      run: |
        pm2 start app.py --name greetings-app-${{ inputs.env_name }} --interpreter venv\Scripts\python.exe -- --port ${{ inputs.port }}