name: run-api-tests
description: Run API tests against selected environment

inputs:
  env_name:
    description: Environment name
    required: true
  tests_path:
    description: Directory where test repo will be cloned
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone API test repository
      uses: actions/checkout@v6
      with:
        repository: mtararujs/course-js-api-framework
        path: ${{ inputs.tests_path }}

    - name: Print test info
      shell: cmd
      run: echo "Running tests on ${{ inputs.env_name }}..."

    - name: Install npm packages
      shell: cmd
      working-directory: ${{ inputs.tests_path }}
      run: npm install

    - name: Run greetings tests
      shell: cmd
      working-directory: ${{ inputs.tests_path }}
      run: npm run greetings greetings_${{ inputs.env_name }}